### ISSUE TITLE
Dealing with order in ViewModel composition 

### ISSUE THREAD

**Issue by chris-pardy** [mauroservienti/all-our-aggregates-are-wrong-demos#1]
@mauroservienti Looking at CartIdAppender it seems like it must be run before other IHandleRequests or the cart-id cookie may not exist, and operations may fail. However I don't see this being dealt with anywhere. Is there a strategy for dealing with this?

**Comment by chris-pardy** [comment]
@mauroservienti thanks. Our real world use case is doing an "look up / insert" on an account.

**Comment by mauroservienti** [comment]
@chris-pardy I raised #2 as a different approach to solve the problem. I haven't changed the logic, but given that now the `CartId` generation is completely disconnected from the `ViewModel Composition` process, it can be changed to whatever different requirement.

**Comment by chris-pardy** [comment]
@mauroservienti I think this approach makes sense. Giving some thought to our use case it feels like this idea works really well with CQRS so you should never have a case of needing to read data from 1 service before you dispatch a command to another service.

**Comment by mauroservienti** [comment]
Agreed. I’ll merge the PR and close this one then, feel free to reopen or raise other issues. Thanks!
