### ISSUE TITLE
[QUESTION] How to implement an archiving service for order history?

### ISSUE THREAD

**Issue by markphillips100** [mauroservienti/all-our-aggregates-are-wrong-demos#146]
My apologies @mauroservienti if this is an inappropriate place to ask this question.  Please let me know where would be a better forum.

I have watched this repository's related YouTube videos with specific interest around the question at https://youtu.be/KkzvQSuYd5I?t=2621. Your answer describes a separate service generating a PDF invoice using appenders to compose the data (view model) to use in a template, the service then persisting the PDF for later client retrieval.

I mention this use case as I think it might be how I would solve the following requirement but I'm not entirely certain.

## The System
So lets say I have a set of services such as in your repository that facilitate an ecommerce mobile application.  The services are deployed in 2 cloud regions, one in the US and one in Europe.  Customers in each region's country are routed to the nearest region.  There is no data replication between the regions.  They are effectively two different ecommerce shops with their own products for sale.

## The Requirement
Customers can travel to both the US and Europe and so can make purchases from both regions under the same identity.  A customer signed into a mobile app using the one identity should be able to see their global order history (receipts) no matter what region their mobile is routing to.

## The Problem
If each region has data isolation then no one region has a view of all orders made by a customer globally.

## A Possible Solution?
Each region should have an OrderHistory service that can listen for OrderCompleted events from Sales to trigger an ArchiveOrder command.  The command handler would use appenders (supplied by the Sales, Marketing, etc) to obtain a model of data to store as an archive record.  After persistence it could publish an OrderArchived event letting the other services know they can delete their CartId related data.

The backing store of the OrderHistory service could be a globally-available store such as CosmosDb or MongoDb where each region's service uses the same database.  No matter the region routed to from the mobile app when viewing order history, the same combined dataset is surfaced to the customer.

This has the added benefit of limiting data in the other services to only those orders that are not complete.

Does this sound like an appropriate solution without breaking SOA principles?  Or do you see simpler alternatives?

Again, apologies if not the place for this question.

**Comment by mauroservienti** [comment]
Thanks for the question @markphillips100, issues are just fine for questions too.

Your proposed solution is a viable solution for sure. In the end, once an order is completed it's set in stone and can be archived as a read-only artifact. In such a case it makes sense to have an order archive service that acts as a client in the system and reacting to order lifecycle events grabs orders details and store them. Data for this service are geo-replicated and clients can connect there.

Another option would do something very similar to what Amazon does, which is showing only orders from a specific region. If one wants to see orders made in a different region they need to explicitly switch region on the website (e.g. moving from amazon.it to amazon.com) or in the app.

**Comment by markphillips100** [comment]
Good to know I'm on a right track.

By the way, your videos on there being no shopping cart I found really useful for communicating to peers who always look at designs purely from the UI perspective.  So thank you for those.

To refer to your response, I had also considered order history to be visible only in the region they originated.  It's something I need to go back to the business about for sure.  Like you said, Amazon do it that way.

When I looked at Uber (as an example of an order payment pipeline) you can view your world-wide trip history no matter the country you are currently in so I guess it's about balancing expectations.  After all, when an order is completed the user is emailed a receipt to it's not like they don't receive the data in some form.

Just to clarify why this has been a problem for me, I guess I'm torn between 2 requirements.  One is attempting to achieve guaranteed at-least-once delivery during the process of order checkout, payment and fulfillment in each workload region, and the other is providing some global aggregation (at some point business will want some global data views across all the isolated region workloads, whether that be for reporting or surfacing data to a customer).

So I've always had the mindset that the architecture needs a SqlDatabase so I can use the Outbox pattern to achieve the first requirement.  Unfortunately using a SqlDatabase usually means a more region-specific database workload which means fulfilling the second requirement of global data aggregation is complex.

I've looked at alternatives to see if I can just start using a globally available, read/write database rather than SqlDatabase.

Using CosmosDb here is out of the question for me.  (I've seen Jimmy Bogard attempt the outbox pattern and it seems complex).  CosmoDb just doesn't have support for transactions across collections.

I did see that MongoDb is supported in NServiceBus for the Outbox pattern so I'm assuming that this is dues to MongoDb's support for distributed transactions now.  I think if I used MongoDb Atlas I could scale each region to its individual workload needs and also locate region-specific data appropriately, whilst also allowing a user to see their data from anywhere.

Considering the business know from the beginning they would want to support multiple countries with low-latency, and possibly providing global aggregation views, is using MongoDb Atlas Global Clusters and the NServiceBus Outbox pattern (+ SAGAs) a viable alternative?

**Comment by mauroservienti** [comment]
> By the way, your videos on there being no shopping cart I found really useful for communicating to peers who always look at designs purely from the UI perspective. So thank you for those.

Thanks, I'm glad they are helpful.

> Considering the business know from the beginning they would want to support multiple countries with low-latency, and possibly providing global aggregation views, is using MongoDb Atlas Global Clusters and the NServiceBus Outbox pattern (+ SAGAs) a viable alternative?

I'm failing to understand what the problem is, I'm probably missing part of the context. Using the Uber use case where the requirement is to allow, in some way, users to view their trip receipts regardless of where they are in the world with the lowest possible latency given that if they are in Europe they'll be connected to the Europe data center, if they are in the US they'll be connected to the US data center.

In the Uber scenario trips are local, users will book a car in the US the trip will be in the US and when done will be store in the US, the receipt at this point is sent in stone, as the order and the entire set of events that occurred during the order processing and during the trip. This means that there is no concurrency, and thus no possible merge conflict, between geo-distributed data centers. Once the trip in the US is over, all US trip data can be synched to Europe as they are effectively read-only at this point.

If this is the case each data center could be using whatever storage technology the prefer to store their data. In each geo-distributed system, there will be handlers subscribed to specific messages/events to store trip processing related information into the read-only geo-replicated storage (e.g. CosmosDB).

Do you have a scenario in which users connected to different data centers are touching the same data set? In which case it's legitimate to expect merge replication conflicts.

What am I missing?

**Comment by markphillips100** [comment]
You Uber scenario description is exactly how I've been thinking.  And indeed yes there is one scenario that's part of the checkout process that requires access to data across data centers.

Here we go...
I have an additional requirement to allow a customer to save their payment methods for use in future orders in all countries the application operates in.

I intend to use Stripe for payments.  Stripe allows storing of Payment Methods against a Customer using their API.  This requires the user has a "customer" identifier in Stripe and is the key used for looking up things like their payment methods.  Note: this identifier is not the same as our internal customer identifier.

Given Stripe's Search API does not support look-ups by any custom metadata, i.e. I cannot lookup by my own BillingService CustomerId, on first save of a payment method I'd have to store the Stripe CustomerId (in BillingService perhaps) thus allowing me to query Stripe later in the context of the user.

The problem here is if the entire checkout process is local data center only, a given customer will get a data center specific Stripe Customer Id and so the view of payment methods is not global.

Any suggestions on how to handle this?  It just feels like that data should be managed by a service with global data storage.

**Comment by mauroservienti** [comment]
It seems to me that to store Stripe identifier a geo-distributed store is a good solution, geo-replicated blob storage is probably the cheapest. You could store Stripe identifiers as metadata on files in blob storage where the file name is your customer ID, which I suppose is unique across the globe.

That being said we could argue that users don't travel (yet) at the speed of light, which means that you could replicate stripe identifiers across data centers using a message over a queue. Users will be slower unless they are me and login first from Europe and immediately after that from the US using a VPN, just to see what happens 😄.

Upon setting up Stripe for a customer a `StripeAccountCreated` message like:

```
{
   "stripeIdentifier": ...,
   "customerIdentifier": ...
}
```

could be sent from the data center where the operation happened to other data centers.

Does it make sense?

**Comment by markphillips100** [comment]
That's interesting.  I'd never considered the blob storage but I can see how that would fit.

I think I prefer the first option if only because it seamlessly caters for a 3rd region coming online after customers are already created.  I wouldn't need to deal with replicating existing data.

I'm finding this really useful so thanks for your input.  I should probably close the issue here though as I think I've deviated from the original title.
