### ISSUE TITLE
Do the demo's service API projects require NSB endpoints?

### ISSUE THREAD

**Issue by markphillips100** [mauroservienti/all-our-aggregates-are-wrong-demos#154]
Do API projects in the demo, such as Sales.Api, require an NSB endpoint registration such as shown [here](https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos/blob/8b6853fb920d4ec6fb885216675551d66a46f658/src/Sales.Api/Startup.cs#L20)?

I thought the intention of these projects was merely to surface data through GET requests initiated from the services viewmodel composition project.  If so then there's no need for an endpoint, or am I missing something?

**Comment by mauroservienti** [comment]
Ah, good catch @markphillips100, thanks.
No that's not needed anymore. That's a leftover from a previous version of the demo when adding items to cart was done through an HTTP POST to Sales.Api: https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos/commit/b34c8910b007564954f90dfdcb450925a4e4c62c

I'll raise a PR to remove NServiceBus from the Sales.Api endpoint.

**Comment by mauroservienti** [comment]
Raised https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos/pull/155 to address this.

**Comment by markphillips100** [comment]
No problem.  Thanks Mauro.
