### ISSUE TITLE
add item to cart error handling IHandleRequestsErrors

### ISSUE THREAD

**Issue by mathysd** [mauroservienti/all-our-aggregates-are-wrong-demos#85]
Let’s say adding an item to a cart failed in the sales handler (ShoppingCartAddPostHandler).
And the server goes down, iis reset, whatever just before OnRequestError was able to do its work?

CleanupFailedCartRequestHandler in Shipping will never get notified that something went wrong and will be in an incorrect state.

Or did I miss something? Why not send events from the sales domain after the shopping cart has been saved successfully?

**Comment by mauroservienti** [comment]
Hi @mathysd, thanks for the question. And yes you’re right, in that scenario the `IHandleRequestsError` is very weak and is NOT the way to (I’ve adjusted the talk based on feedback as it was a bit misleading). The original intention was to keep it simple but as you correctly notice it’s not really the right solution.

I wrote a blog post about this very topic detailing all scenarios and what’s the optimal approach: https://milestone.topics.it/2019/05/02/safety-first.html

Let me know what you think.

**Comment by mathysd** [comment]
Thansk for the blog post! I read the other posts on viewmodel composition as well. 

What’s reason for making the composition gateway responsible for "orchestrating" between the services? You could have the sales domain raising events when the quantity of an item has changed.

**Comment by mauroservienti** [comment]
>Thanks for the blog post! I read the other posts on viewmodel composition as well.

Great, if you have questions, please, do not hesitate to raise follow up issues. Or comment on the blogpost if comments are still open.

>What’s reason for making the composition gateway responsible for "orchestrating" between the services? You could have the sales domain raising events when the quantity of an item has changed.

It’s mostly, it not only, a coupling reason. You don’t want services that are not dependent on each other to become coupled. If Sales is the one that publishes information about quantity changes then Sales ends up being coupled to any subscriber, making Sales evolution harder and harder the larger this coupling surface is.

Does it make sense?

**Comment by mathysd** [comment]
Yes that makes sense. To me the composition gateway sounds like a backend-for-frontend. So any other composition gateway would have to include this behavior as well.

**Comment by mauroservienti** [comment]
My experience with backend-for-frontend architecture is kinda limited, I’ve focused myself on Composition Gateways. Anyway I guess you’re right, a CG is a kind of backend-for-frontend.

**Comment by mauroservienti** [comment]
I recently merged a change to move all write attempts to use messaging: https://github.com/mauroservienti/all-our-aggregates-are-wrong-demos/pull/101

Based on that I'm going to close this issue. Feel free to re-open and raise another one if you have any further question. Thanks!
